### ISSUE TITLE
Pull request templates

### ISSUE THREAD

**Issue by banartdev** [variocube/devtools#10]
### Current Behaviour

We do not have pull request templates in our repositories.

### Desired Behaviour

After updating devtools in any of our repositories, a pull request template is linked into the `.github` directory. The pull request template should contain the following items.

---

Refs issue-number-or-link

Related PRs:
 - issue-number-or-link
 - issue-number-or-link

Additional notes:
 - add some additional notes here

## Coder

 - [ ] I paid attention to the warnings and errors the IDE gave me and I have fixed them where appropriate
 - [ ] I wrote unit/integration tests where applicable
 - [ ] I tested that the issue is resolved
 - [ ] I tested that no regressions were introduced (other features still work)
 - [ ] I tested edge cases
 - [ ] I tested error cases and errors are handled correctly
 - [ ] The build and tests have succeeded
 - [ ] There are no conflicts with the main / master branch

## Reviewer

Code review:
 - [ ] The coder completed their checklist to a reasonable extend (relative to the complexity of the PR)
 - [ ] I have reviewed the code and it is easy to understand and follows best practices.

Testing:
 - [ ] I have tested that the issue is resolved
 - [ ] I have tested that no regressions were introduced (other features still work)
 - [ ] I have tested edge cases
 - [ ] I have tested error cases and errors are handled correctly

Merging:
 - [ ] I have resolved any database version conflicts
 - [ ] The build and tests have succeeded
 - [ ] I have moved the issue to *Waiting Deployment*

**Comment by steima** [comment]
If you work on a project do `./devtools.sh update` 2x.
