### ISSUE TITLE
Database authentication

### ISSUE THREAD

**Issue by peterkarrer** [variocube/devtools#4]
## Summary

On a debian-based system there is no password authentication for the `root` user. One would rather run the `mysql` command with `sudo` when accessing the database as root.

There are two possible solutions:
 - Run the `mysql` command with `sudo` if the developer does not specify a password at the prompt
 - Use the application's credentials; either by reading them from the application profile (not easy to parse) or from the `.vc` file (easy, but duplicate).

## Tasks

 - [ ] Task 1
 - [ ] Task 2

**Comment by dhauber** [comment]
I implemented the first solution:

> Run the `mysql` command with `sudo` if the developer does not specify a password at the prompt
